set positional-arguments := true

default:
    @just --list

test: _start && _stop
    #!/bin/bash

    source ../common.sh
    highlight "\nRunning tests in $PWD\n\n"
    for test in $(grep ^_test_ Justfile | cut -d':' -f1);
    do
        highlight "$test "
        just $test && true || err "Stopping."
    done

_start dirname="." +args="-d":
    #!/bin/bash
    function wait_docker() {
        while [ $(docker ps | grep $1 | wc -l) -eq 0 ]; do
          sleep 0.1
        done
    }
    docker run -p 9000:9000 --name minio -d minio/minio server /export && wait_docker "minio"
    docker run --rm -it --net=host -v $(realpath .mc):/root/.mc --entrypoint=mc minio/mc mb myminio/test-bucket
    docker run --rm -it --net=host -v $(realpath .mc):/root/.mc -v $(realpath .):/src --entrypoint=mc minio/mc cp /src/binary_file.tar.gz.part1 myminio/test-bucket/binary_file.tar.gz.part1

_stop dirname=".":
    @docker rm --force minio > /dev/null 2>&1

_test:
    true
